### ISSUE TITLE
3D model

### ISSUE THREAD

**Issue by Guru-02** [I-div-Even-2021/Repo-08#14]

**Comment by Guru-02** [comment]
![20210717_101134-COLLAGE](https://user-images.githubusercontent.com/84072990/126025830-fae6a739-e598-4fcc-8e0b-125c673ef51a.jpg)

**Comment by Guru-02** [comment]
![Screenshot 2021-07-16 115432](https://user-images.githubusercontent.com/84072990/126025855-5d84fb54-d1e2-48a0-870a-9e814c53ac3d.png)

**Comment by Guru-02** [comment]
[rope walking bot (1).zip](https://github.com/I-div-Even-2021/Repo-08/files/6890172/rope.walking.bot.1.zip)

**Comment by N-Soumya** [comment]
Clamp: 
![Autodesk Inventor Professional 2021 28-07-2021 14_01_52 (2)](https://user-images.githubusercontent.com/83869157/127293132-42cc6796-febe-42e7-8882-c069bdc63475.png)
Gear train;
![Autodesk Inventor Professional 2021 28-07-2021 14_04_56 (2)](https://user-images.githubusercontent.com/83869157/127293203-2f208182-448d-41b5-853e-e79928d8e353.png)
Bottom: 
![Autodesk Inventor Professional 2021 28-07-2021 14_06_29 (2)](https://user-images.githubusercontent.com/83869157/127293301-7536b509-8c8e-425f-8bfc-f7ff0e53b260.png)
Payload:
![7 Virtual Implementation · I-div-Even-2021_Repo-08 Wiki and 2 more pages - Personal - Microsoft​ Edge 28-07-2021 14_20_56 (3)](https://user-images.githubusercontent.com/83869157/127293785-c89fd618-5767-491d-89f6-2fb1948032a3.png)
DC motor:
![7 Virtual Implementation · I-div-Even-2021_Repo-08 Wiki and 2 more pages - Personal - Microsoft​ Edge 28-07-2021 14_20_56 (2)](https://user-images.githubusercontent.com/83869157/127293822-e1265337-1d82-4811-b961-25ffb57834ce.png)
